core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.AuthView.as_view(), name='auth'),
    path('home', views.HomeView.as_view(), name='home'),
    path('best-sellers', views.BestSellersView.as_view(), name='best_sellers'),
    path('most-expensives', views.MostExpensivesItemsView.as_view(), name='most_expensive_items'),
    path('logout', views.LogoutView.as_view(), name='logout'),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
]

urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import TemplateView, RedirectView

from api.mercado_libre.items import get_best_sellers_by_item_category, get_most_expensives_by_category
from api.mercado_libre.user import get_logged_user_data, get_user_detail_by_id


class AuthView(TemplateView):
    template_name = 'core/auth.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.GET.get('code'):
                request.session['code'] = request.GET['code']
            elif 'code' or 'user' not in request.session:
                return render(request, self.template_name)

            request.session['user'] = get_logged_user_data(request)
            return HttpResponseRedirect(reverse('core:home'))
        except Exception as e:
            messages.error(request, str(e))
            return render(request, self.template_name)


class LogoutView(RedirectView):
    def get(self, request, *args, **kwargs):
        for key in list(request.session.keys()):
            del request.session[key]
        request.session.set_expiry(-2)
        return HttpResponseRedirect(reverse('core:auth'))


class HomeView(TemplateView):
    template_name = 'core/home.html'


class BestSellersView(TemplateView):
    template_name = 'core/best_sellers.html'

    def get(self, request, *args, **kwargs):
        try:
            items = get_best_sellers_by_item_category('MLA352679')
            sorted_list = sorted(items, key=lambda x: x['sold_quantity'], reverse=True)

            # getting more seller details
            for item in sorted_list:
                seller_detail = get_user_detail_by_id(item['seller']['id'])
                item['seller'] = seller_detail

            return render(request, self.template_name, {'items': sorted_list[:5]})

        except Exception as e:
            messages.error(request, str(e))
            return render(request, self.template_name)


class MostExpensivesItemsView(TemplateView):
    template_name = 'core/most_expensives.html'

    def get(self, request, *args, **kwargs):
        try:
            items = get_most_expensives_by_category('MLA352679')
            return render(request, self.template_name, {'items': items['results'][:20]})

        except Exception as e:
            messages.error(request, str(e))
            return render(request, self.template_name)

core/templates/core/auth.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block sidebar %}{% endblock %}
{% block header %}{% endblock %}

{% block extra_css %}
    <style>
        body {
            background-color: lightgray !important;
        }
    </style>
{% endblock %}

{% block clean_content %}

    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <div class="text-center mb-2">
                        <img src="https://http2.mlstatic.com/frontend-assets/ui-navigation/5.10.1/mercadolibre/logo-pt__large_plus.png"
                             alt="">
                    </div>

                    <div class="p-5 pt-0">
                        <h5 class="">Would you like to authenticate in your Mercado Libre
                            account?</h5>
                        <br>
                        <a href="https://auth.mercadolivre.com.br/authorization?response_type=code&client_id=4824734347650288&redirect_uri=http://localhost:8000"
                           class="btn btn-info text-center btn-block">Continue <i class="fa fa-arrow-right"></i></a>
                    </div>
                    <div class="text-center">
                        <a class="text-center text-muted" href="{% url 'core:home' %}">Maybe later</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>

{% endblock %}

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>

    <title>{% block title %}  {% endblock %}</title>

    {% include 'core/includes/_head.html' %}

    {% block extra_css %}{% endblock %}

</head>

<body class="c-app">

{% block sidebar %}
    {% include 'core/includes/_sidebar.html' %}
{% endblock %}

<div class="c-wrapper c-fixed-components">

    {% block header %}
        {% include 'core/includes/_header.html' %}
    {% endblock %}

    <div class="c-body pt-lg-3">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        {% block clean_content %}{% endblock %}
    </div>

</div>

{% include 'core/includes/_js.html' %}

{% block extra_js %}{% endblock %}

</body>

core/templates/core/best_sellers.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Best sellers by category{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'core/css/user-cards.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="">Bets sellers in "Smartwatches" </h4>
                </div>
            </div>

        </div>

        {% for item in items %}
            <div class="col-lg-4">
                <div class="text-center card-box">
                    <div class="member-card pt-2 pb-2">
                        <div class="thumb-lg member-thumb mx-auto">
                            {% if item.seller.logo %}
                                <img src="{{ item.seller.logo }}" class="rounded-circle img-thumbnail"
                                     alt="profile-image">
                            {% else %}
                                <i class="fa fa-4x fa-user-circle"></i>
                            {% endif %}
                        </div>
                        <div class="">
                            <h4>{{ item.seller.nickname }}</h4>
                        </div>
                        <a target="_blank" href="{{ item.seller.permalink }}"
                           class="btn btn-primary mt-3 btn-rounded waves-effect w-md waves-light">View Profile</a>
                        <div class="mt-4">
                            <div class="row">
                                <div class="col-6">
                                    <div class="mt-3">
                                        <h4>{{ item.available_quantity }}</h4>
                                        <p class="mb-0 text-muted">Available</p>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="mt-3">
                                        <h4>{{ item.sold_quantity }}</h4>
                                        <p class="mb-0 text-muted">Sold</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="row mt-5">
        <div class="col-sm-2"></div>
        <div class="col-sm-4">
            <a class="text-decoration-none" style="color: inherit" href="{% url 'core:best_sellers' %}">
                <div class="card overflow-hidden">
                    <div class="card-body p-0 d-flex align-items-center">
                        <div style="background-color: #fff159" class="py-4 px-5 mfe-3">
                            <i class="fa fa-3x fa-user-check"></i>
                        </div>
                        <div>
                            <div class="text-muted text-uppercase font-weight-bold small">Best sellers by category</div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-4">
            <a class="text-decoration-none" style="color: inherit" href="{% url 'core:most_expensive_items' %}">
                <div class="card overflow-hidden">
                    <div class="card-body p-0 d-flex align-items-center">
                        <div style="background-color: #fff159" class=" py-4 px-5 mfe-3">
                            <i class="fa fa-3x fa-dollar-sign"></i>
                        </div>
                        <div>
                            <div class="text-muted text-uppercase font-weight-bold small">Most expensive by category
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-2"></div>
    </div>


{% endblock %}

core/templates/core/includes/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<link rel="stylesheet" href="{% static 'core/css/style.css' %}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"  />

<!-- DATETIMEPICKER -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.min.css"
      rel="stylesheet"/>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/font-awesome-line-awesome/css/all.min.css"/>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css"/>

core/templates/core/includes/_header.html
<header class="c-header c-header-light c-header-fixed c-header-with-subheader">
    <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar"
            data-class="c-sidebar-show">
        <i class="fa fa-bars"></i>
    </button>
    <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar"
            data-class="c-sidebar-lg-show">
        <i class="fa fa-bars"></i>
    </button>

    <ul class="c-header-nav ml-auto mr-4">
        <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-link" data-toggle="dropdown" href="#"
               role="button" aria-haspopup="true" aria-expanded="false">
                <h5 class="mt-0">
                    {% if request.session.user %}
                        {{ request.session.user.nickname }}
                    {% else %}
                        Anonymous user
                    {% endif %}
                </h5>
                <div class="c-avatar">
                    <i class="fa fa-user"></i>
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
                <div class="dropdown-header bg-light py-2"><strong>Account</strong></div>
                {% if request.session.user %}
                <a class="dropdown-item" href="{% url 'core:logout' %}">
                    <i class="fa fa-external-link-alt"></i> Log out</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'core:auth' %}">
                    <i class="fa fa-key"></i> Log in</a>
                {% endif %}
            </div>
        </li>
    </ul>

</header>

core/templates/core/includes/_js.html
{% load static %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>


<script type="application/javascript">
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-bottom-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    {% for message in messages %}
        toastr['{{ message.tags }}']('{{ message }}');
    {% endfor %}

</script>

core/templates/core/includes/_sidebar.html
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
    <div class="c-sidebar-brand d-lg-down-none">
        <h3 class="m-0">TPD</h3>
    </div>
    <ul class="c-sidebar-nav">
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{% url 'core:home' %}">
                <i class="c-sidebar-nav-icon fa fa-home"></i> Home</a>
        </li>
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{% url 'core:best_sellers' %}">
                <i class="c-sidebar-nav-icon fa fa-user-check"></i> Best sellers by category </a>
        </li>
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{% url 'core:most_expensive_items' %}">
                <i class="c-sidebar-nav-icon fa fa-dollar-sign"></i> Most expensive by category </a>
        </li>
    </ul>
</div>

core/templates/core/most_expensives.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Most expensive by category{% endblock %}

{% block content %}

    <div class="row ">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="">Most expensives items in "Smartwatches" </h4>
                </div>
            </div>

        </div>
        <div class="col-sm-12">

            {% for item in items %}

                <div class="card mb-0 border-bottom">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-2">
                                <a class="text-decoration-none" target="_blank" href="{{ item.permalink }}">
                                    <img width="130" height="130" src="{{ item.thumbnail }}"
                                         class="ui-search-result-image__element" alt="{{ item.title }}">
                                </a>
                            </div>
                            <div class="col-sm-10">
                                <a class="text-decoration-none" target="_blank" href="{{ item.permalink }}">
                                    <h5 class="text-muted">{{ item.title }}</h5>
                                </a>
                                <h3>$ {{ item.price|floatformat|intcomma }}</h3>
                            </div>
                        </div>
                    </div>
                </div>


            {% endfor %}

        </div>
    </div>

{% endblock %}